/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _APP_H_RPCGEN
#define _APP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct print_data {
	char buffer[1024];
	int size;
};
typedef struct print_data print_data;

#define TEST 0x21000000
#define VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define PROCEDURE 1
extern  int * procedure_1(print_data *, CLIENT *);
extern  int * procedure_1_svc(print_data *, struct svc_req *);
extern int test_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PROCEDURE 1
extern  int * procedure_1();
extern  int * procedure_1_svc();
extern int test_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_print_data (XDR *, print_data*);

#else /* K&R C */
extern bool_t xdr_print_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_APP_H_RPCGEN */
