/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "app.h"
#include <stdlib.h>
#include <unistd.h>
#include <strings.h>

#define PORT    8080 
#define MAXLINE 1024 

void testowy_1(char *host)
{
	CLIENT *clnt;
	print_data printer_struct;
	int sockfd; 
	char buffer[MAXLINE]; 
	struct sockaddr_in servaddr, cliaddr; 
	
	
    // Creating socket file descriptor 
    if ( (sockfd = socket(AF_INET, SOCK_DGRAM, 0)) < 0 ) { 
        perror("socket creation failed"); 
        exit(EXIT_FAILURE); 
    } 
      
    memset(&servaddr, 0, sizeof(servaddr)); 
    memset(&cliaddr, 0, sizeof(cliaddr)); 
      
    // Filling server information 
    servaddr.sin_family    = AF_INET; // IPv4 
    servaddr.sin_addr.s_addr = INADDR_ANY; 
    servaddr.sin_port = htons(PORT); 
      
    // Bind the socket with the server address 
    if ( bind(sockfd, (const struct sockaddr *)&servaddr,  
            sizeof(servaddr)) < 0 ) 
    { 
        perror("bind failed"); 
        exit(EXIT_FAILURE); 
    } 
    

#ifndef DEBUG
	clnt = clnt_create(host, TEST, VERSION, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */

	while ((printer_struct.size = read(STDIN_FILENO, printer_struct.buffer, 1024)) > 0)
	{
		int* result = procedure_1(&printer_struct, clnt);
		if (result == NULL)
		{
			clnt_perror(clnt, "call failed");
		}
		bzero(printer_struct.buffer,1024);
		
		int len, n; 
  
		len = sizeof(cliaddr);  //len is value/resuslt 
		n = recvfrom(sockfd, (char *)buffer, MAXLINE,  
                MSG_WAITALL, ( struct sockaddr *) &cliaddr, 
                &len); 
		buffer[n] = '\0';
		printf("%s\n", buffer);
		fflush(stdout);
		bzero(buffer,1024);
	}

#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[])
{
	char *host;

	if (argc < 2)
	{
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	// printf("%d %d\n", atoi(argv[2]), atoi(argv[3]));
	testowy_1(host);
	exit(0);
}
